name: Make Tarball
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Make-tarball:
    runs-on: ubuntu-latest
    env:
      TARBALL_NAME: pdf-detective.tar
    steps:
      - name: Print info
        run: |
          echo "The job was automatically triggered by a ${{ github.event_name }} event."
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Print debug info
        run: |
          echo "github.event: ${{ github.event }}"
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.head_ref: ${{ github.head_ref }}"
          echo "github.ref: ${{ github.ref }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.ref_type: ${{ github.ref_type }}"
          echo "github.triggering_actor: ${{ github.triggering_actor }}"
          echo "github.workflow: ${{ github.workflow }}"
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Make tarball
        run: tar -vcf ${TARBALL_NAME} pdf-detective pdf-detective.py Pipfile
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Stage tarball
        run: git add ${TARBALL_NAME}
      - name: Commit tarball
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m 'auto-commit updated tarball'
      - name: check git
        run: |
          git status
          git branch -v
          git remote -v
      - name: Push to branch
        run: git push origin ${{ github.head_ref }}
      - run: echo "This job's status is ${{ job.status }}."
